IF
	!InPartyAllowDead(Myself)
	OR(2)
		Global("MaltisinParty","LOCALS",0)
		Global("MaltisinParty","LOCALS",2)
	OR(2)
		TimeOfDay(DAY)
		TimeOfDay(MORNING)
THEN
	RESPONSE #100
		Deactivate(Myself)
		ChangeAIScript("MADEAKT",OVERRIDE)
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
	XPGT(Player1,189000)
	XPLT(Player1,300000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMacht","LOCALS",1)
		AddXPObject(Myself,100000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
	!Global("MalthisXPCheck","GLOBAL",1)
	XPGT(Player1,189000)
	XPLT(Player1,300000)
THEN
	RESPONSE #100
		SetGlobal("MalthisMacht","LOCALS",1)
		AddXPObject(Myself,100000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
	!Global("MalthisXPCheck","GLOBAL",1)
	XPGT(Player1,299999)
	XPLT(Player1,600000)
THEN
	RESPONSE #100
		SetGlobal("MalthisMacht","LOCALS",1)
		AddXPObject(Myself,250000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
	!Global("MalthisXPCheck","GLOBAL",1)
	XPGT(Player1,599999)
	XPLT(Player1,1000000)
THEN
	RESPONSE #100
		SetGlobal("MalthisMacht","LOCALS",1)
		AddXPObject(Myself,700000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
	!Global("MalthisXPCheck","GLOBAL",1)
	XPGT(Player1,999999)
	XPLT(Player1,1500000)
THEN
	RESPONSE #100
		SetGlobal("MalthisMacht","LOCALS",1)
		AddXPObject(Myself,1000000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
	!Global("MalthisXPCheck","GLOBAL",1)
	XPGT(Player1,1499999)
	XPLT(Player1,2000000)
THEN
	RESPONSE #100
		SetGlobal("MalthisMacht","LOCALS",1)
		AddXPObject(Myself,1500000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
	!Global("MalthisXPCheck","GLOBAL",1)
	XPGT(Player1,1999999)
	XPLT(Player1,2950000)
THEN
	RESPONSE #100
		SetGlobal("MalthisMacht","LOCALS",1)
		AddXPObject(Myself,2000000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMacht","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("MalthisMacht","LOCALS",1)
		SetGlobal("MalthisXPCheck","GLOBAL",1)
END

IF
	InParty(Myself)
	Global("MaBoeserWeg","LOCALS",2)
	Global("MaBekommtVampir1","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("MaBekommtVampir1","LOCALS",1)
		AddSpecialAbility("MVAMPIR1") // Verwandelt in einen Wolf
		AddSpecialAbility("MVAMPIR1") // Verwandelt in einen Wolf
		AddSpecialAbility("MVAMPIR1") // Verwandelt in einen Wolf
END

IF
	Global("MaBekommtVampir1","LOCALS",1)
	OR(1)
		TimeOfDay(DAY)
	AreaType(OUTDOOR)
	!AreaCheck("AR0322")
	!AreaCheck("AR0323")
	!AreaCheck("AR1404")
	!HasItem("MWOLFVAM",Myself) // Angriff
	!HasItem("MWOLKE",Myself) // Angriff
	Delay(5)
THEN
	RESPONSE #100
		ApplyDamage(Myself,10,MAGICFIRE)
		DisplayStringHead(Myself,@1) // No such index
END

IF
	GlobalLT("Chapter","GLOBAL",4)
	InParty(Myself)
	Global("MalthisVampirZähler","LOCALS",0)
	RandomNum(10,10)
THEN
	RESPONSE #100
		SetGlobal("MalthisVampirZähler","LOCALS",1)
		SetGlobalTimer("MalthisTimerTrans","LOCALS",280)
		Continue()
END

IF
	InParty(Myself)
	GlobalTimerExpired("MalthisTimerTrans","LOCALS")
	Global("MalthisVampirZähler","LOCALS",1)
	CombatCounter(0)
	OR(3)
		TimeOfDay(MORNING)
		TimeOfDay(NIGHT)
		TimeOfDay(DUSK)
	AreaType(OUTDOOR)
	!AreaCheck("AR0322")
	!AreaCheck("AR0323")
	!AreaCheck("AR0041")
	!AreaCheck("AR0042")
	!AreaCheck("AR0043")
	!AreaCheck("AR0044")
	!AreaCheck("AR0045")
	!AreaCheck("AR0046")
	!AreaCheck("AR0400")
	LOS([PC],12)
THEN
	RESPONSE #100
		SetGlobal("MalthisVampirZähler","LOCALS",2)
		ClearAllActions()
		StartCutSceneMode()
		Wait(2)
		StartCutScene("MCUT01")
		Continue()
END

IF
	InParty(Myself)
	Global("Malthiserzählt","LOCALS",1)
	Global("MaltisinParty","LOCALS",1)
THEN
	RESPONSE #100
		IncrementGlobal("Malthiserzählt","LOCALS",1)
		SetGlobalTimer("MalthisTimerGeschichte","LOCALS",THREE_DAYS)
END

IF
	InParty(Myself)
	GlobalTimerExpired("MalthisTimerGeschichte","LOCALS")
	Global("Malthiserzählt","LOCALS",2)
	Global("MaBio","LOCALS",0)
	CombatCounter(0)
	LOS([PC],12)
	Delay(10)
THEN
	RESPONSE #100
		SetGlobal("MaBio","LOCALS",1)
		StartDialogueNoSet(Player1)
END

IF
	LOS([PC],25)
	Global("MalthisDieb","LOCALS",0)
	CombatCounter(0)
THEN
	RESPONSE #100
		SetGlobal("MalthisDieb","LOCALS",1)
		CreateCreatureObject("MFeind1",Myself,1,1,1) // Straßenräuber der Schattendiebe
END

IF
	See("MFeind1")
	!Dead("MFeind1") // Straßenräuber der Schattendiebe
THEN
	RESPONSE #100
		Attack("MFeind1")
END

IF
	Global("MaltisinParty","LOCALS",0)
	NumTimesTalkedTo(0)
	Dead("MFeind1") // Straßenräuber der Schattendiebe
	LOS([PC],25)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	InParty(Myself)
	Global("MaltisinParty","LOCALS",2)
	LOS(Player1,12)
THEN
	RESPONSE #100
		SetDialog("MaltJ")
		StartDialogueNoSet(Player1)
END

IF
	InParty(Myself)
	Dead("MCapt01") // Ritter des Ordens
	Dead("MSold01") // Söldner
	Dead("MSold02") // Söldner
	Dead("MSold03") // Söldner
	Global("MalthisReaktionRitter","LOCALS",0)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	InParty(Myself)
	GlobalTimerExpired("MaKontakt","GLOBAL")
	Global("MaMecker","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("MaMecker","GLOBAL",1)
END

IF
	InParty(Myself)
	AreaCheck("AR0513")
	Global("MaKontaktmann","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("MaKontaktmann","LOCALS",1)
		CreateCreatureObject("MKontakt",Myself,1,1,1) // Kontaktmann der Gilde
		ActionOverride("MKontakt",StartDialogueNoSet("Malt"))
END

IF
	InParty(Myself)
	Global("MaKontaktmann","LOCALS",1)
	Global("MaCutScene2","LOCALS",0)
	OR(3)
		TimeOfDay(MORNING)
		TimeOfDay(NIGHT)
		TimeOfDay(DUSK)
	AreaType(OUTDOOR)
	!AreaCheck("AR0322")
	!AreaCheck("AR0323")
	!AreaCheck("AR0041")
	!AreaCheck("AR0042")
	!AreaCheck("AR0043")
	!AreaCheck("AR0044")
	!AreaCheck("AR0045")
	!AreaCheck("AR0046")
	!AreaCheck("AR0400")
	CombatCounter(0)
	LOS([PC],12)
	Delay(20)
THEN
	RESPONSE #100
		SetGlobal("MaCutScene2","LOCALS",1)
		ClearAllActions()
		StartCutSceneMode()
		Wait(2)
		StartCutScene("MCUT02")
		Continue()
END

IF
	InParty(Myself)
	Dead("MKern") // Kern - Ritter des Ordens
	Dead("MDindal") // Dindal - Ritter des Ordens
	Dead("MSold04") // Söldner
	Dead("MSold05") // Söldner
	Dead("MDruide") // Schattendruide
	Global("MalthisReaktionRitter","LOCALS",2)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	InParty(Myself)
	OR(3)
		TimeOfDay(MORNING)
		TimeOfDay(NIGHT)
		TimeOfDay(DUSK)
	AreaType(OUTDOOR)
	!AreaCheck("AR0322")
	!AreaCheck("AR0323")
	!AreaCheck("AR0041")
	!AreaCheck("AR0042")
	!AreaCheck("AR0043")
	!AreaCheck("AR0044")
	!AreaCheck("AR0045")
	!AreaCheck("AR0046")
	!AreaCheck("AR0400")
	Global("MaEndeFinale","LOCALS",0)
	GlobalTimerExpired("MaFinalerKampf","GLOBAL")
	CombatCounter(0)
	LOS([PC],12)
	RandomNum(10,10)
THEN
	RESPONSE #100
		SetGlobal("MaEndeFinale","LOCALS",1)
		ClearAllActions()
		StartCutSceneMode()
		Wait(2)
		StartCutScene("MCUT03")
		Continue()
END

IF
	InParty(Myself)
	Dead("mfinal01") // Vampyr
	Dead("mfinal02") // Vampyr
	Dead("mfinal03") // Vampyr
	Global("MaEndeFinale","LOCALS",1)
	OR(2)
		Global("MaBoeserWeg","LOCALS",0)
		!Global("MaBoeserWeg","LOCALS",0)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	OR(12)
		AreaCheck("AR0203")
		AreaCheck("AR0319")
		AreaCheck("AR0408")
		AreaCheck("AR0512")
		AreaCheck("AR0703")
		AreaCheck("AR0901")
		AreaCheck("AR0902")
		AreaCheck("AR0903")
		AreaCheck("AR1010")
		AreaCheck("AR2008")
		AreaCheck("AR2803")
		AreaCheck("AR2812")
	!HasItem("MWOLFVAM",Myself) // Angriff
	!HasItem("MWOLKE",Myself) // Angriff
	Global("MaBekommtVampir1","LOCALS",1)
	Delay(5)
THEN
	RESPONSE #100
		ApplyDamage(Myself,10,FIRE)
		DisplayStringHead(Myself,@2) // No such index
END

IF
	AreaCheck("AR4000")
	Global("MaDialogsetzenToB","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("MaDialogsetzenToB","LOCALS",1)
		SetDialog("Multig")
END

IF
	OR(17)
		HasItem("npsw03",Myself) // Geheiligter Rächer
		HasItem("sw2h10",Myself) // Carsomyr +5
		HasItem("miscau",Myself) // Elfisches Heiliges Wasser
		HasItem("misc4x",Myself) // Lathanderstatuette
		HasItem("Misc5a",Myself) // Teil der Dimensionsreißers
		HasItem("Misc5b",Myself) // Teil der Dimensionsreißers
		HasItem("Misc5c",Myself) // Dimensionsreißer
		HasItem("Misc5z",Myself) // Dimensionsreißer
		HasItem("Misc6g",Myself) // Büste Sunes
		HasItem("Misc6q",Myself) // Amuanas Knochen
		HasItem("Misc81",Myself) // Schädel von Kereph
		HasItem("Miscb1",Myself) // Talisman Rillifanes
		HasItem("Key04",Myself) // Sonnenstrahlsymbol
		HasItem("Key05",Myself) // Morgenlichtsymbol
		HasItem("Key06",Myself) // Lichtsteinsymbol
		HasItem("Key23",Myself) // Symbol Amaunators
		HasItem("Amul23",Myself) // Peridot des Lebens
	!HasItem("MWOLFVAM",Myself) // Angriff
	!HasItem("MWOLKE",Myself) // Angriff
	Global("MaBekommtVampir1","LOCALS",1)
	Delay(5)
THEN
	RESPONSE #100
		ApplyDamage(Myself,10,FIRE)
		DisplayString(Myself,42935) // Oooh, das tut weh!
		GiveItem("npsw03",Player1) // Geheiligter Rächer
		GiveItem("sw2h10",Player1) // Carsomyr +5
		GiveItem("miscau",Player1) // Elfisches Heiliges Wasser
		GiveItem("misc4x",Player1) // Lathanderstatuette
		GiveItem("Misc5a",Player1) // Teil der Dimensionsreißers
		GiveItem("Misc5b",Player1) // Teil der Dimensionsreißers
		GiveItem("Misc5c",Player1) // Dimensionsreißer
		GiveItem("Misc5z",Player1) // Dimensionsreißer
		GiveItem("Misc6g",Player1) // Büste Sunes
		GiveItem("Misc81",Player1) // Schädel von Kereph
		GiveItem("Key04",Player1) // Sonnenstrahlsymbol
		GiveItem("Key05",Player1) // Morgenlichtsymbol
		GiveItem("Key06",Player1) // Lichtsteinsymbol
		GiveItem("Key23",Player1) // Symbol Amaunators
		GiveItem("Amul23",Player1) // Peridot des Lebens
END

IF
	Global("MaWeitereVerwandlungen","LOCALS",1)
	Global("MaEndeFinale","LOCALS",2)
THEN
	RESPONSE #100
		SetGlobal("MaWeitereVerwandlungen","LOCALS",2)
		SetGlobalTimer("MaTimerWeitereVerwandlungen","LOCALS",FOUR_DAYS)
END

IF
	HasItem("MWOLFVAM",Myself) // Angriff
	Global("MaBekommtVampir1","LOCALS",1)
	Global("MaZeitWolfform","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("MaZeitWolfform","LOCALS",1)
		RealSetGlobalTimer("MaDauerWolfsform","GLOBAL",1200)
END

IF
	!HasItem("MWOLFVAM",Myself) // Angriff
	!RealGlobalTimerExpired("MaDauerWolfsform","GLOBAL")
	Global("MaZeitWolfform","LOCALS",1)
	Global("MaBekommtVampir1","LOCALS",1)
THEN
	RESPONSE #100
		SetGlobal("MaZeitWolfform","LOCALS",0)
END

IF
	HasItem("MWOLFVAM",Myself) // Angriff
	RealGlobalTimerExpired("MaDauerWolfsform","GLOBAL")
	Global("MaZeitWolfform","LOCALS",1)
	Global("MaBekommtVampir1","LOCALS",1)
	GlobalLT("MaWolfFähigkeit4mal","LOCALS",4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,@3) // No such index
		IncrementGlobal("MaWolfFähigkeit4mal","LOCALS",1)
		AddSpecialAbility("MWOLF") // Wolfwere beschwören
		SetGlobal("MaZeitWolfform","LOCALS",0)
END

IF
	Global("MaWolfFähigkeit4mal","LOCALS",1)
	Global("MaJournalWolfeinmal","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("MaJournalWolfeinmal","LOCALS",1)
		AddJournalEntry(@4,INFO)
END

IF
	See([ENEMY])
	ActuallyInCombat()
	Global("MaltimKampf","LOCALS",0)
	GlobalLT("MaltAnzahlimKampf","LOCALS",5)
	HasItem("MRING4",Myself) // Ring
THEN
	RESPONSE #100
		SetGlobal("MaltimKampf","LOCALS",1)
		IncrementGlobal("MaltAnzahlimKampf","LOCALS",1)
END

IF
	!See([ENEMY])
	!ActuallyInCombat()
	Global("MaltimKampf","LOCALS",1)
	HasItem("MRING4",Myself) // Ring
THEN
	RESPONSE #100
		SetGlobal("MaltimKampf","LOCALS",0)
END

IF
	CombatCounter(0)
	LOS(Player1,12)
	Global("MaGaswolkegut","LOCALS",0)
	Global("MaltAnzahlimKampf","LOCALS",5)
	HasItem("MRING4",Myself) // Ring
THEN
	RESPONSE #100
		SetGlobal("MaGaswolkegut","LOCALS",1)
		AddJournalEntry(@5,INFO)
		AddSpecialAbility("MWOLKE1") // Selbstverwandlung: Gaswolke
END

IF
	Or(2)	
		HitBy([ANYONE],FIRE)
		HitBy([ANYONE],0001)	
	Global("M_Schaden_schwer_reg","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("M_Schaden_schwer_reg","GLOBAL",1)
END

IF
	Global("M_Schaden_schwer_reg","GLOBAL",1)
	Global("M_Schadensmeldung_Reg","LOCALS",0)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END
	