IF
	InParty(Myself)
	Global("MalthisMachtToB","LOCALS",0)
	XPGT(Player1,189000)
	XPLT(Player1,300000)
	XP(Myself,189000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMachtToB","LOCALS",1)
		AddXPObject(Myself,100000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMachtToB","LOCALS",0)
	XPGT(Player1,299999)
	XPLT(Player1,600000)
	XP(Myself,189000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMachtToB","LOCALS",1)
		AddXPObject(Myself,250000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMachtToB","LOCALS",0)
	XPGT(Player1,599999)
	XPLT(Player1,1000000)
	XP(Myself,189000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMachtToB","LOCALS",1)
		AddXPObject(Myself,700000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMachtToB","LOCALS",0)
	XPGT(Player1,999999)
	XPLT(Player1,1500000)
	XP(Myself,189000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMachtToB","LOCALS",1)
		AddXPObject(Myself,1000000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMachtToB","LOCALS",0)
	XPGT(Player1,1499999)
	XPLT(Player1,2000000)
	XP(Myself,189000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMachtToB","LOCALS",1)
		AddXPObject(Myself,1500000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMachtToB","LOCALS",0)
	XPGT(Player1,1999999)
	XPLT(Player1,2950000)
	XP(Myself,189000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMachtToB","LOCALS",1)
		AddXPObject(Myself,2000000)
		Continue()
END

IF
	InParty(Myself)
	Global("MalthisMachtToB","LOCALS",0)
	XPGT(Player1,2949999)
	XP(Myself,189000)
THEN
	RESPONSE #100
		IncrementGlobal("MalthisMachtToB","LOCALS",1)
		AddXPObject(Myself,3000000)
		Continue()
END

IF
	See([PC])
	NumTimesTalkedTo(0)
THEN
	RESPONSE #100
		StartDialogueNoSet(Player1)
END

IF
	!InParty(Myself)
	Global("MalthisMachtToB","LOCALS",1)
THEN
	RESPONSE #100
		SetDialog("Multig")
END

IF
	Or(2)
		Global("MaBekommtVampir1","LOCALS",1)
		Alignment("Malt",MASK_EVIL)
	TimeOfDay(DAY)
	AreaType(OUTDOOR)
	!HasItem("MWOLFVAM",Myself) // Angriff
	!HasItem("MWOLKE",Myself) // Angriff
	Delay(5)
THEN
	RESPONSE #100
		ApplyDamage(Myself,20,MAGICFIRE)
		DisplayStringHead(Myself,@1) // Ahh, die Sonne verbrennt mich...
END

IF
	OR(2)
		HitBy([ANYONE],FIRE)
		HitBy([ANYONE],0001)
	Global("M_Schaden_schwer_reg","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("M_Schaden_schwer_reg","GLOBAL",1)
END
